### ISSUE TITLE
AttributeError: 'ActionParams' object has no attribute 'affected_services_with_changes'

### ISSUE THREAD

**Issue by ngrundler** [cybot16/NED-Miration-Utility#2]
Using this tool to attempt a migration on a Juniper device and it's failing with the following traceback:

```
Traceback (most recent call last):
  File "/home/grundler/src/NED-Miration-Utility/./ned_migration.py", line 633, in <module>
    ned_migrate(root, device, new_ned_id, dry_run , no_networking)
  File "/home/grundler/src/NED-Miration-Utility/./ned_migration.py", line 472, in ned_migrate
    if device_migrate_dr_result.affected_services.as_list() or device_migrate_dr_result.affected_services_with_changes.as_list():
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 478, in __getattr__
    super(Node, self).__getattribute__(name)
AttributeError: 'ActionParams' object has no attribute 'affected_services_with_changes'
```

This is from an NSO 5.6.3.1 system-install.

**Comment by ngrundler** [comment]
Checking `tailf-ncs-devices.yang`, the `affected-services-with-changes` leaf was removed in 5.6:

```
...
  revision 2021-09-02 {                                                                                                                                                                                                                                                                                                       
    description                                                                                                                                                                                                                                                                                                               
      "Released as part of NCS-5.6.

      Non-backwards-compatible changes have been introduced. 

      ...

      Updated the description of the 'affected-services' leaf in the                                                                                                                                                                                                                                                         
      migrate action output parameters.                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                              
      Removed the 'affected-services-with-changes' leaf in the                                                                                                                                                                                                                                                               
      migrate action output parameters.    

      ...
}  
...
```

**Comment by rd101010** [comment]
Also see this on a local install of 5.7.6.2 against a Cisco iosxr netsim.

**Comment by Markhamm** [comment]
#3 
Hi, the above PR should fix the issue.
As you have noticed, in NSO 5.6 and later, the 'affected-services' leaf has been removed, the PR is emulating the old behavior however performances are quite bad as we need to scan backpointers for each device config in order to identifiy if some of the modified paths proposed by the new NED impact the device config.
We have warned the BU about this behavior and an ongoing request has been made to change the behavior of the "migrate" command.

**Comment by Markhamm** [comment]
#4 
As been added.
It fixes several things and improve the perf + avoid the need the of Maagic patch.
